## Riddle Me ⚡⚡️
### Return in a finally Block

Consider this java code snippet, what is the output?
 
 ```java
public String doSomething() {  
    String name = "David";
    try {
        throw new IOException();
    } finally {
        return name;
    }
}
 ```
 
In this case, even though the try block throws a new IOException, we use return in the finally block, ending it abruptly. This causes the try block to end abruptly due to the return statement, and not the IOException, essentially dropping the exception in the process.

> #92
